---

- name: "POST | Flush Handlers"
  tags: always
  ansible.builtin.meta: flush_handlers

- name: "POST | Reboot System Options"
  vars:
    warn_control_id: Reboot_Required
  tags:
    - always
  block:
    - name: "POST | Rebooting System................. skip_reboot Has Been Set To: False"
      when:
        - reboot_host
        - not skip_reboot
      ansible.windows.win_reboot:
        reboot_timeout: 3600

    - name: "POST | Warning A Reboot Is Required, Skip Reboot Has Been Set"
      when:
        - reboot_host
        - skip_reboot
      ansible.builtin.debug:
        msg:
          - "Warning!! Changes have been made that require a reboot to be implemented manually."
          - "skip_reboot was set to: True (This can affect compliance check results)"
      changed_when: true

    - name: "POST | Warning A Reboot Is Required, skip_reboot Has Been Set | Warning Count"
      when:
        - reboot_host
        - skip_reboot
      ansible.builtin.import_tasks:
        file: warning_facts.yml
