---

# THE FOLLOWING 4 CONTROLS WILL FAIL UNLESS THEY ARE IN THE FOLLOWING ORDER FOR CLOUD-BASED SYSTEMS
# CONTROL 1.2.2, CONTROL 1.2.4, CONTROL 1.2.1, CONTROL 1.2.3
- name: "1.2.2 | PATCH | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0."
  when: win19cis_rule_1_2_2
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_1.2.2
    - patch
    - account
    - gpo
    - NIST800-171_3.1.8
    - NIST800-171_3.1.18
    - NIST800-53_AC-7
    - NIST800-53_AC-19
    - NIST800-53R5_AC-7
    - NIST800-53R5_AC-19
  block:
    - name: "1.2.2 | PATCH | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0. | Set Variable."
      when:
        - win19cis_bad_login_lockout_count <= 5
        - win19cis_bad_login_lockout_count > 0
      community.windows.win_security_policy:
        section: System Access
        key: LockoutBadCount
        value: "{{ win19cis_bad_login_lockout_count }}"

    - name: "1.2.2 | AUDIT | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0. | Verify Variable Not 0 or more then 5 warning."
      when:
        - win19cis_bad_login_lockout_count > 5 or
          win19cis_bad_login_lockout_count == 0
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid number of attempts set for win19cis_bad_login_lockout_count please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."

    - name: "1.2.2 | AUDIT | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0. | Set warning count."
      when:
        - win19cis_bad_login_lockout_count > 5 or
          win19cis_bad_login_lockout_count == 0
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: '1.2.2'

- name: "1.2.1 | AUDIT | Ensure Account lockout duration is set to 15 or more minutes"
  when: win19cis_rule_1_2_1
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_1.2.1
    - patch
    - account
    - gpo
    - NIST800-171_3.1.8
    - NIST800-171_3.1.18
    - NIST800-53_AC-7
    - NIST800-53_AC-19
    - NIST800-53R5_AC-7
    - NIST800-53R5_AC-19
  block:
    - name: "1.2.1 | PATCH | Ensure Account lockout duration is set to 15 or more minutes. | Set Variable"
      when: win19cis_account_lockout_duration >= 15
      community.windows.win_security_policy:
        section: System Access
        key: LockoutDuration
        value: "{{ win19cis_account_lockout_duration }}"

    - name: "1.2.1 | AUDIT | Ensure Account lockout duration is set to 15 or more minutes. | Verify variable set to 15 or more minutes warning."
      when: win19cis_account_lockout_duration < 15
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid number of minutes set for win19cis_account_lockout_duration please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."

    - name: "1.2.1 | AUDIT | Ensure Account lockout duration is set to 15 or more minutes. | Set warning count."
      vars:
        warn_control_id: '1.2.1'
      when: win19cis_account_lockout_duration < 15
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "1.2.3 | PATCH | Ensure Allow Administrator account lockout is set to Enabled"
  when:
    - win19cis_rule_1_2_3
    - prelim_win19cis_is_domain_member
  tags:
    - level1-memberserver
    - rule_1.2.3
    - patch
    - password
    - gpo
    - NIST800-171_3.1.8
    - NIST800-171_3.1.18
    - NIST800-53_AC-7
    - NIST800-53_AC-19
    - NIST800-53R5_AC-7
    - NIST800-53R5_AC-19
  community.windows.win_security_policy:
    section: System Access
    key: AllowAdministratorLockout
    value: "{{ win19cis_allow_admin_account_lockout }}"

- name: "1.2.4 | PATCH | Ensure Reset account lockout counter after is set to 15 or more minutes."
  when: win19cis_rule_1_2_4
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_1.2.4
    - patch
    - account
    - gpo
    - NIST800-171_3.1.8
    - NIST800-171_3.1.18
    - NIST800-53_AC-7
    - NIST800-53_AC-19
    - NIST800-53R5_AC-7
    - NIST800-53R5_AC-19
  block:
    - name: "1.2.4 | PATCH | Ensure Reset account lockout counter after is set to 15 or more minutes. | Set Variable."
      when:
        - win19cis_account_lockout_counter_reset >= 15
        - win19cis_account_lockout_counter_reset <= win19cis_account_lockout_duration
      community.windows.win_security_policy:
        section: System Access
        key: ResetLockoutCount
        value: "{{ win19cis_account_lockout_counter_reset }}"

    - name: "1.2.4 | AUDIT | Ensure Reset account lockout counter after is set to 15 or more minutes. | Verify variable set to 15 or more minutes warning."
      when:
        - win19cis_account_lockout_counter_reset > win19cis_account_lockout_duration or
          win19cis_account_lockout_counter_reset < 15
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid number of minutes set for win19cis_account_lockout_counter_reset please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."

    - name: "1.2.4 | AUDIT | Ensure Reset account lockout counter after is set to 15 or more minutes. | Set warning count."
      vars:
        warn_control_id: '1.2.4'
      when:
        - win19cis_account_lockout_counter_reset > win19cis_account_lockout_duration or
          win19cis_account_lockout_counter_reset < 15
      ansible.builtin.import_tasks:
        file: warning_facts.yml
