prefix         = "githubLE-win-cis"
location       = "eastus"
tagname        = "github_LE_actions"
system_size    = "Standard_DC4s_v2"
OS_publisher   = "MicrosoftWindowsServer"
OS_version     = "2019"
system_release = "datacenter-gensecond"
hostname       = "LE2019"
