# This is a basic workflow to help you get started with Actions

name: Update Galaxy

# Controls when the action will run.
# Triggers the workflow on push or pull request
# events but only for the devel branch
on:
  push:
    branches:
      - main

jobs:
  update_role:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout V4
        uses: actions/checkout@v4

      - name: Update Galaxy
        uses: ansible-actions/ansible-galaxy-action@main
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
          git_branch: main
